### ISSUE TITLE
Provided addgroup and adduser cmds don't work for Ubuntu based images

### ISSUE THREAD

**Issue by radupopa2010** [hexops/dockerfile#13]
This docker cmd
`RUN addgroup -g 10001 -S nonroot && adduser -u 10000 -S -G nonroot -h /home/nonroot nonroot`
does not work for Ubuntu based images. 
Got error like:

```
 > [stage-1 5/9] RUN addgroup -g 10001 -S nonroot && adduser -u 10000 -S -G nonroot -h /home/nonroot nonroot:                             
#9 0.427 Option g is ambiguous (gecos, gid, group)
#9 0.427 Option s is ambiguous (shell, system)
```
`addgroup` on Ubuntu desktop doesn't have same arguments like the ones provided in the docker file

Replaced it with:
```
RUN groupadd --gid 10001 nonroot && \
         useradd  --home-dir /home/nonroot \
                        --shell /bin/bash \
                        --create-home
                        --gid nonroot \
                        --groups nonroot \
                        --uid 10000 nonroot
```

Please let me know if I got the mapping right. I don't know what `-S` argument represents in your cmd

**Comment by fernandodev** [comment]
His image is based on `alpine:latest` 

https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user

```
addgroup [-g GID] [-S] [USER] GROUP
```

**Comment by radupopa2010** [comment]
Ok, it seems I got it right. Thanks for the wiki link @fernandodev 
I will close this issue
