### ISSUE TITLE
Add a license to this repository

### ISSUE THREAD

**Issue by Calinou** [hexops/dockerfile#7]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by emidoots** [comment]
@Calinou Absolutely, no problem. I've added our standard Apache + MIT dual licensing to this repository in 5fb2f6a5be433ed8fde3aa828952ae18e5e9d2a6. 

Thank you for flagging!
