### ISSUE TITLE
Static UID and GID on OpenShift

### ISSUE THREAD

**Issue by charliesolomon** [hexops/dockerfile#9]
I’m interested in your thoughts on building images for platforms like Red Hat OpenShift, which override the UID/GID of the image when a container is run (using an unpredictable, high UID).  This adds security, but causes problems with file permissions unless the image author builds in permission fixes.
I haven’t found a simple to implement, general best practice that works with these platforms... it’s usually some hacky chmod script acting on application specific folders/files.

**Comment by emidoots** [comment]
Hello! Unfortunately I'm not too familiar with OpenShift. If they set the UID/GID containers run as to unpredictable high UIDs, that actually seems like a great security boon. I imagine it does have the issue you described, though, where introspecting from the host machine (i.e. outside the container) is quite difficult. I suspect that on those platforms:

- Sharing files with the host does not make sense at all (i.e. embracing containerization fully, including for data.)
- Introspecting files from the host itself does not make sense, rather doing so from a shell within the container is probably expected.

This is not too dissimilar to [Docker user namespace isolation](https://docs.docker.com/engine/security/userns-remap/) or [Kubernetes' security context functionality](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), both of which override UID/GIDs for improved security.

This doesn't really change what you should do _in your Dockerfile_, though. If you still want it to be as secure as possible on the widest array of containerization platforms out there - using a static, high UID/GID with a non-root user as in the `Dockerfile` example in this repository is still a really good idea.

**Comment by charliesolomon** [comment]
Thank you, I appreciate the response!
